create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key(id)
);

/*

** H2 다운로드 **

https://www.h2database.com/html/main.html


** H2 실행 **
cd h2/bin
chmod 755 h2.sh
./h2.sh

** JDBC URL 설정 **

첫 실행시
jdbc:h2:~/test
home 경로에 test.mv.db 파일이 생겼는지 확인

그 이후부터는
jdbc:h2:tcp://localhost/~/test
로 연결

 */